version = 0.1

[default]
[default.global.parameters]
stack_name = "advolt-dev"
region = "ap-south-1"
profile = "voltai"

[default.deploy.parameters]
stack_name = "advolt-dev"
s3_bucket = ""
s3_prefix = "advolt"
region = "ap-south-1"
profile = "voltai"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "Stage=dev",
  "OpenAIApiKey=dummy_openai_key",
  "ClaudeApiKey=dummy_claude_key",
  "RazorpayKey=dummy_razorpay_key",
  "RazorpaySecret=dummy_razorpay_secret",
  "RazorpayWebhookSecret=dummy_webhook_secret",
  "GeminiApiKey=AQ.Ab8RN6IXGtlCBc-Iv8BBOGJ2wM0nG1l24tWwNPkcbJAZugtqaQ",
  "GroqApiKey=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"
]
confirm_changeset = true
resolve_s3 = true

[staging.deploy.parameters]
stack_name = "advolt-staging"
region = "ap-south-1"
profile = "voltai"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "Stage=staging"
]

[prod.deploy.parameters]
stack_name = "advolt-prod"
region = "ap-south-1"
profile = "voltai"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "Stage=prod"
]
confirm_changeset = true
